name: Grafana Agent
version: 1.0.0
slug: grafana_agent
description: Set up grafana agent to send data to Grafana Cloud
arch:
  - aarch64
  - armv7
  - amd64
init: false
# host_pid: true
apparmor: true
auth_api: true
hassio_api: true
homeassistant_api: true
hassio_role: admin
schema:
  remote_write_url: str
  remote_write_username: str
  remote_write_password: password
